// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZatratyCore.Models;

public partial class Autorize
{
    public int Id { get; set; }

    public string Login { get; set; }

    public string Password { get; set; }

    public int FillialId { get; set; }

    public string Employee { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public string Primechanie { get; set; }

    public int? Admin { get; set; }

    public virtual Fillial Fillial { get; set; }
}