// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZatratyCore.Models;

public partial class FillialsExpense
{
    public int Id { get; set; }

    public DateTime? Date { get; set; }

    public int? FillialId { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public string Primechanie { get; set; }

    public virtual Fillial Fillial { get; set; }

    public virtual ICollection<TableFillialsExpense> TableFillialsExpenses { get; set; } = new List<TableFillialsExpense>();
}