// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZatratyCore.Models;

public partial class Fillial
{
    public int Id { get; set; }

    public string Filial { get; set; }

    public string Primechanie { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public virtual ICollection<Autorize> Autorizes { get; set; } = new List<Autorize>();

    public virtual ICollection<FillialsExpense> FillialsExpenses { get; set; } = new List<FillialsExpense>();

    public virtual ICollection<Form4F> Form4Fs { get; set; } = new List<Form4F>();

    public virtual ICollection<Role> Roles { get; set; } = new List<Role>();
}