// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZatratyCore.Models;

public partial class GetExp
{
    public string FullName { get; set; }

    public int Id { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public string Primechanie { get; set; }
}