// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZatratyCore.Models;

public class ReportHtml
{
    public string Id { get; set; }
    public int? S { get; set; }
    public int? Po { get; set; }
    public int Year { get; set; }
    public int Period { get; set; }
    public List<int> Zatraty {  get; set; }   
}
