// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZatratyCore.Models;

public partial class TableFillialsExpense
{
    public int Id { get; set; }

    public int? FillialExpensesId { get; set; }

    public int? PlanId { get; set; }

    public int? ExpensesId { get; set; }

    public decimal? Value { get; set; }

    public string UserMod { get; set; }

    public DateTime? DateMod { get; set; }

    public string Primechanie { get; set; }

    public virtual Expense Expenses { get; set; }

    public virtual FillialsExpense FillialExpenses { get; set; }

    public virtual Plan Plan { get; set; }
}