// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ZatratyCore.Models;

public class VMLogin
{
    public string Login { get; set; }
    public string PassWord { get; set; }
    public string Admin { get; set; }
    //public bool KeepLoggedIn { get; set; }
}
